name: Publish
on:
  workflow_run:
    workflows: [release-please]
    types: [completed]
    
jobs:
  release-please:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@webspaceiq'

      - run: npm ci

      - name: Set package registry
        run: npm config set registry https://npm.pkg.github.com

      - name: Github package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PUBLISH_TOKEN }}
        
      - name: Publish the package to Github and Npm package registries
        run: npm publish


